version: "3"
services:
  app:
    image: node:latest
    working_dir: /usr/src/app
    tty: true # keep container alive without default command
    ports:
      - "3000:3000"
    volumes:
      ["./:/usr/src/app", "node-modules:/usr/src/app/node_modules"]
volumes:
  node-modules:
